name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # Links to your GitHub Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}  # Pull from environment variables
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Debug Variables
        run: |
          echo "ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}"
          echo "ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}"
          echo "AWS_REGION: ${{ vars.AWS_REGION }}"
          echo "IMAGE_TAG: ${{ github.sha }}"
          echo "Full tag: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}"
      
      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # Dynamic from ECR login
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}  # From GitHub Settings
          IMAGE_TAG: ${{ github.sha }}  # Commit SHA
        run: |
          FULL_TAG="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          FULL_TAG_LATEST="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
          
          docker build -t "$FULL_TAG" .
          docker tag "$FULL_TAG" "$FULL_TAG_LATEST"
          
          docker push "$FULL_TAG"
          docker push "$FULL_TAG_LATEST"